	# Create database studentproject
	create database studentproject;
	
	#USED DATABASE
	use studentproject;
	
	#CREATE STUDENT TABLE
	create table STUDENT(STUDENT_NO VARCHAR(3) PRIMARY KEY,STUDENT_NAME TEXT(10),STUDENT_DOB DATE,STUDENT_DOJ DATE);
	
       #CRAETE PROJECT TABLE
       create table PROJECT(PRJ_NO VARCHAR(3) PRIMARY KEY,PRJ_NAME TEXT(3),PRJ_DUR INT,PRJ_PLATFORM TEXT(10));
       
	# CREATE 3rd TABLE TO SHOW RELATION 
	CREATE TABLE STUDENTPROJECT(STUDENT_NO VARCHAR(3),PRJ_NO VARCHAR(3),DESIGNATION TEXT(10),FOREIGN KEY(STUDENT_NO) REFERENCES STUDENT(STUDENT_NO),FOREIGN KEY(PRJ_NO)REFERENCES PROJECT(PRJ_NO));

